python_code_analyzer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('python_code_analyzer_app.urls')),
]

python_code_analyzer_app/urls.py
"""Defines URL patterns for python_code_analyzer_app."""

from django.urls import path

from . import views

app_name = 'python_code_analyzer_app'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all Repositories.
    path('repositories/', views.repositories, name='repositories'),
    # Detail page for a single repository.
    path('repositories/<int:repository_id>/', views.repository, name='repository'),
    # Page for adding a new repository
    path('new_repository/', views.new_repository, name='new_repository'),
    # Page for adding a repositories in a massive way
    path('massive_upload/', views.massive_upload, name='massive_upload'),
    # Page for adding a new analysis
    path('new_analysis/<int:repository_id>/', views.new_analysis, name='new_analysis'),
    # Detail page for a single analysis.
    path('analyzes/<int:analysis_id>/', views.analysis, name='analysis'),
    # Reult page for a single analysis.
    path('analysis_result/<int:analysis_id>/', views.analysis_result, name='analysis_result'),
    # Cancel a single analysis.
    path('cancel_analysis/<int:analysis_id>/', views.cancel_analysis, name='cancel_analysis'),
    # Delete a single analysis.
    path('delete_analysis/<int:analysis_id>/', views.delete_analysis, name='delete_analysis'),
    # Delete a single repository.
    path('delete_repository/<int:repo_id>/', views.delete_repository, name='delete_repository'),
    # Delete a all analizes.
    path('delete_all_analyzes/<int:repo_id>/', views.delete_all_analyzes, name='delete_all_analyzes'),
    # Delete a all repositories.
    path('delete_all_repositories/', views.delete_all_repositories, name='delete_all_repositories'),
]

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
 # Include default auth urls.
 path('', include('django.contrib.auth.urls')),
 # Registration page.
 path('register/', views.register, name='register'),
]

python_code_analyzer_app/models.py
from python_code_analyzer_app.app_models.Analysis import Analysis, CeleryTaskSignal
from python_code_analyzer_app.app_models.Repository import Repository
from python_code_analyzer_app.app_models.Tool import Tool
from python_code_analyzer_app.app_models.AnalysisTool import AnalysisTool

python_code_analyzer_app/forms.py
from django import forms

from .models import Repository, Analysis, AnalysisTool

class RepositoryForm(forms.ModelForm):
    class Meta:
        model = Repository
        fields = ['url']
        labels = {'url': 'Repository url'}

class AnalysisForm(forms.ModelForm):
    class Meta:
        model = Analysis
        fields = ['status']
        labels = {'status':'Status'}
        # widgets = {
        #     'herramientas':forms.CheckboxSelectMultiple()
        # }

    def __init__(self, *args, **kwargs): 
        super(AnalysisForm, self).__init__(*args, **kwargs)                       
        self.fields['status'].disabled = True

class AnalysisToolForm(forms.ModelForm):
    class Meta:
            model = AnalysisTool
            fields = ['tool']
            labels = {
                'tool':'Tool'
            }

    # def __init__(self, *args, **kwargs): 
    #     super(AnalysisToolForm, self).__init__(*args, **kwargs)                       
    #     self.fields['tool_id'].disabled = True
    #     self.fields['parameters'].disabled = True

class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField()

python_code_analyzer_app/views.py
import os
from django.conf import settings

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from python_code_analyzer_app.app_layout_classes.LayoutManager import LayoutManager

from python_code_analyzer_app.app_models.TaskManager import TaskManager
from python_code_analyzer.celery import app

from .models import Repository, Analysis, Tool, AnalysisTool, CeleryTaskSignal
from .forms import RepositoryForm, AnalysisForm, AnalysisToolForm, UploadFileForm

from django.core.paginator import Paginator

def index(request):
    """The home page for Python Code Analyzer."""
    return render(request, 'python_code_analyzer_app/index.html')

@login_required
def repositories(request):
    """Show all repositories."""
    #Set up pagination
    p = Paginator(Repository.objects.filter(owner=request.user).order_by('date_added'), 8)
    page = request.GET.get('page')
    repos = p.get_page(page)
    context = {'repositories': repos}
    return render(request, 'python_code_analyzer_app/repositories.html', context)

@login_required
def repository(request, repository_id):
    """Show a single repository and all its analyzes."""
    repository = Repository.objects.get(id=repository_id)
    # Make sure the repository belongs to the current user.
    if repository.owner != request.user:
        raise Http404
    analyzes = repository.analysis_set.order_by('-date_added')
    p = Paginator(repository.analysis_set.order_by('-date_added'), 8)
    page = request.GET.get('page')
    analyzes = p.get_page(page)
    context = {'repository': repository, 'analyzes': analyzes}
    return render(request, 'python_code_analyzer_app/repository.html', context)

@login_required
def new_repository(request):
    """Add a new repository."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = RepositoryForm()
    else:
        # POST data submitted; process data.
        form = RepositoryForm(data=request.POST)
        if form.is_valid():
            new_repository = form.save(commit=False)
            new_repository.owner = request.user
            new_repository.save()
            return redirect('python_code_analyzer_app:repositories')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'python_code_analyzer_app/new_repository.html', context)

@login_required
def massive_upload(request):
    """Add a repositories from file."""
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            f = request.FILES['file']
            txt_file=os.path.join(settings.BASE_PATH,"massive.txt")
            with open(txt_file, 'wb+') as destination:
                for chunk in f.chunks():
                    destination.write(chunk)
            task_id = TaskManager.launch_massive_upload.apply_async((txt_file,request.user.id,),countdown=5,queue='repository_queue')
            return redirect('python_code_analyzer_app:repositories')
    else:
        form = UploadFileForm()
    return render(request, 'python_code_analyzer_app/massive_upload.html', {'form': form})

@login_required
def new_analysis(request, repository_id):
    """Add a new analysis for a particular repository."""
    repository = Repository.objects.get(id=repository_id)
    all_tools = Tool.objects.all()

 
    if request.method != 'POST':
        form = AnalysisForm()
    else:
        form = AnalysisForm(data=request.POST)
        if form.is_valid():
            new_analysis = form.save(commit=False)
            new_analysis.repository = repository
            new_analysis.save()
            for x in all_tools:
                habilitado = request.POST.get(f"chk_enabled-{x.id}")
                if habilitado =='clicked':
                    at = AnalysisTool()
                    at.analysis = new_analysis
                    at.tool = x
                    at.save()
            # launch asynchronous task
            print(f"new_analysis - launching the task")
            task_id = TaskManager.excecute_analysis.apply_async((new_analysis.id,),countdown=5)
            print(f"new_analysis - saving task_id = {task_id}")
            new_analysis.task_id=task_id
            new_analysis.save()
            return redirect('python_code_analyzer_app:repository', repository_id=repository_id)
    # Display a blank or invalid form.
    context = {'repository': repository, 'form': form, 'all_tools': all_tools }
    return render(request, 'python_code_analyzer_app/new_analysis.html', context)

@login_required
def analysis(request, analysis_id):
    """Show a single analysis detail"""
    analysis = Analysis.objects.get(id=analysis_id)
    result_items=[]
    result_items=analysis.get_result()
    criteria_list = settings.CRITERIA_LIST
    result_items_ordered = LayoutManager.sort_by_multiple_criteria(result_items,criteria_list)
    context = {'analysis': analysis, 'result_items': result_items_ordered}
    return render(request, 'python_code_analyzer_app/analysis.html', context)

@login_required
def analysis_result(request, analysis_id):
    """Show a single analysis detail"""
    analysis = Analysis.objects.get(id=analysis_id)
    path_to_file = analysis.path_to_zip
    if os.path.exists(path_to_file):
        with open(path_to_file, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/force-download")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(path_to_file)
            return response
    raise Http404

@login_required
def cancel_analysis(request, analysis_id):
    print("Cancel Analysis")
    """Cancel a single analysis"""
    analysis = Analysis.objects.get(id=analysis_id)
    print(f"cancel_analysis - analysis.id: {analysis.id}")
    cts = CeleryTaskSignal()
    cts.analysis = analysis
    cts.signal = CeleryTaskSignal.CANCEL_TASK

    cts.save()
    analysis.cancel("Canceled by user")
    # Redirigir a la misma página
    return redirect(request.META['HTTP_REFERER'])

@login_required
def delete_analysis(request, analysis_id):
    analysis = Analysis.objects.get(id=analysis_id)
    analysis.delete_files()
    analysis.delete()
    # Redirigir a la misma página
    return redirect(request.META['HTTP_REFERER'])

@login_required
def delete_repository(request, repo_id):
    repo = Repository.objects.get(id=repo_id)
    repo.delete_files()
    repo.delete()
    # Redirigir a la misma página
    return redirect(request.META['HTTP_REFERER'])

@login_required
def delete_all_analyzes(request, repo_id):
    repo = Repository.objects.get(id=repo_id)
    analizes = Analysis.objects.filter(repository=repo)
    for a in analizes:
        a.delete_files()
        a.delete()
    return redirect(request.META['HTTP_REFERER'])

@login_required
def delete_all_repositories(request):
    repos = Repository.objects.filter(owner=request.user)
    for r in repos:
        r.delete_files()
        r.delete()
    return redirect(request.META['HTTP_REFERER'])

python_code_analyzer_app/templates/python_code_analyzer_app/analysis.html
{% extends 'python_code_analyzer_app/base.html' %}

{% block page_header %}
<nav class="navbar navbar-dark bg-dark">
	<a  href="javascript:history.go(-1);"  class="btn btn-dark" title="Back"><i class="fa fa-arrow-left"></i></a>
	<span class="navbar-brand h5">Analysis id: <span style="background-color: #5c5c5c">{{ analysis.id }}</span></span>
	<span class="nav-item">Commit: <span style="background-color: #5c5c5c">{{ analysis.commit }}</span></span>
	<span class="nav-item">Status: <span style="background-color: #5c5c5c">{{ analysis.status }}</span></span>
	<span class="nav-item">Date: <span style="background-color: #5c5c5c">{{ analysis.date_added }}</span></span>
	<span class="nav-item">
		{% if analysis.status == 'FINISHED' %}
			<form class="form-inline">
				<a  href="{% url 'python_code_analyzer_app:analysis_result' analysis.id %}"  class="btn btn-dark" title="Download results"><i class="fa fa-download"></i></a>
			</form>
		{% endif %}
	</span>
  </nav>

{% endblock page_header %}
{% block content %}

<div class="mb-2"style="margin-top: 20;">
	<div class='row'>
		{% for item in result_items %}
			{% include item.plantilla with item=item %}
		{% endfor %}
	</div>
</div>
{% endblock content %}

python_code_analyzer_app/templates/python_code_analyzer_app/base.html
{% load bootstrap4 %}
 <!doctype html>
 <html lang="en">
     <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
     <title>Python Code Analyzer</title>
     {% bootstrap_css %}
     {% bootstrap_javascript jquery='full' %}
     <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/chartjs-chart-matrix@1.1"></script>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

<body class="text-light" style="background-color: #343a40;">
 <nav class="navbar navbar-expand-md navbar-dark mb-0 border-dark">
    <a class="navbar-brand" href="{% url 'python_code_analyzer_app:index'%}">
        Python Code Analyzer</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
            <a class="nav-link" href="{% url 'python_code_analyzer_app:repositories'%}">
                Repositories</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text text-light">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
            {% endif %}
        </ul>
    </div>
 </nav>
 <div class="border-bottom mb-2">
        
 </div>
 <main role="main" class="container">
    <div>
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
 </main>
 <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content bg-dark">
        <div class="modal-header">
          <h5 class="modal-title" id="delete-modal-label">Delete item</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            Are you sure you want to delete this item?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <a href="#" id="delete-modal-btn" class="btn btn-danger">Delete</a>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="delete-all-modal" tabindex="-1" role="dialog" aria-labelledby="delete-all-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content bg-dark">
        <div class="modal-header">
          <h5 class="modal-title" id="delete-all-modal-label">Delete all</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            Are you sure you want to delete all items?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <a href="#" id="delete-all-modal-btn" class="btn btn-danger">Delete</a>
        </div>
      </div>
    </div>
  </div>
 <script type="text/javascript">
     $(document).ready(function(){
        {% block jquery %} {% endblock %}
     })

    $(document).on('click', '.delete-btn', function () {
        var url = $(this).data('url');
        $('#delete-modal').modal('show');
        $('#delete-modal-btn').attr('href', url);
    });

    $(document).on('click', '.delete-all-btn', function () {
        var url = $(this).data('url');
        $('#delete-all-modal').modal('show');
        $('#delete-all-modal-btn').attr('href', url);
    });

 </script>
</body>
</html>

python_code_analyzer_app/templates/python_code_analyzer_app/index.html
{% extends "python_code_analyzer_app/base.html" %}

{% block page_header %}
	<div class="jumbotron text-dark">
		<h1 class="display-3">Improve your code!</h1>
		<p class="lead">Analyze, improve, and optimize your Python code with Python Code Analyzer.</p>
		{% if user.is_authenticated %}
		<a class="btn btn-lg btn-primary" href="{% url 'python_code_analyzer_app:repositories' %}"
			role="button">Repositories &raquo;</a>
		{% else %}
		<a class="btn btn-lg btn-primary" href="{% url 'users:login' %}"
			role="button">Log In &raquo;</a>
		<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
			role="button">Register &raquo;</a>
		{% endif %}
	</div>
{% endblock page_header %}

{% block content %}
<p></p>
{% endblock content %}

python_code_analyzer_app/templates/python_code_analyzer_app/massive_upload.html
{% extends "python_code_analyzer_app/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<nav class="navbar-dark bg-dark">
	<span class="navbar-brand mb-0 h1"><a href="javascript:history.go(-1);" class="btn btn-dark" title="Back"><i class="fa fa-arrow-left"></i></a></span>
	<span class="navbar-brand mb-0 h1">Uploading file</span></span>
</nav>
{% endblock page_header %}
{% block content %}
	<div style="width: 700px; padding: 10px; margin-left: 5px;"  > 
		<form action="{% url 'python_code_analyzer_app:massive_upload' %}" enctype="multipart/form-data" method='post'>
			{% csrf_token %}
			{% bootstrap_form form %}
			{% buttons %}
			<div style="text-align: right;">
				<button name="submit" class="btn btn-primary">Upload</button>
			</div>
			{% endbuttons %}
		</form>
	</div>
 
{% endblock content %}

python_code_analyzer_app/templates/python_code_analyzer_app/new_analysis.html
{% extends "python_code_analyzer_app/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
<nav class="navbar-dark bg-dark">
	<span class="navbar-brand mb-0 h1"><a href="javascript:history.go(-1);" class="btn btn-dark" title="Back"><i class="fa fa-arrow-left"></i></a></span>
	<span class="navbar-brand mb-0 h1">Adding new analysis to repository: <span style="background-color: #5c5c5c">{{ repository }}</span></span>
</nav>
{% endblock page_header %}

{% block content %}
	<div style="width: 300px; padding: 10px; margin-left: 15px;"  >
		<form action="{% url 'python_code_analyzer_app:new_analysis' repository.id %}" method='post' >
			{% csrf_token %}
			{% bootstrap_form form %}
		
			<ul class="list-unstyled">
				{% for herr in all_tools %}
				<li>
					<div class="form-group">
						<label class="mb-0">{{herr.name}}:</label>
						<div class="custom-control custom-checkbox" style="margin-left: 40px;">
							<input type="checkbox" class="custom-control-input" value="clicked" name="chk_enabled-{{herr.id}}" id="chk_enabled-{{herr.id}}" checked>
							<label class="custom-control-label" for="chk_enabled-{{herr.id}}">Enabled</label>
						</div>
						<!-- <div class="custom-control custom-checkbox">
							<input type="checkbox" class="custom-control-input" value="clicked" name="chk_default-{{herr.id}}" id="chk_default-{{herr.id}}" checked>
							<label class="custom-control-label" for="chk_default-{{herr.id}}">Parámetros por defecto</label>
						</div>
						<div class="form-group">
								<label for="parameters-{{herr.id}}">Parámetros:</label>
								<input type="text" class="form-control" name="parameters-{{herr.id}}" maxlength="256" id="parameters-{{herr.id}}">
						</div> -->
					</div>
				</li>
				{% endfor %}
			</ul>
				{% buttons %}
				<div style="text-align: right;">
					<button type="submit" class="btn btn-primary" style="display: inline-block; text-align: right;">Add</button>
				</div>
				{% endbuttons %}
			</div>
		</form>
	</div>

{% endblock content %}

python_code_analyzer_app/templates/python_code_analyzer_app/repositories.html
{% extends "python_code_analyzer_app/base.html" %}
{% block page_header %}
<nav class="navbar navbar-dark bg-dark">
	<span class="navbar-brand mb-0 h1">Repositories</span>
	<div class="row">
		<form class="form-inline">
			<a href="{% url 'python_code_analyzer_app:new_repository' %}" class="btn btn-dark" title="New repository"><i class="fa fa-plus"></i></a>
			<a href="{% url 'python_code_analyzer_app:massive_upload' %}" class="btn btn-dark" title="Upload from file"><i class="fa fa-upload"></i></a>
		</form>
		<button class="btn btn-dark delete-all-btn" data-url="{% url 'python_code_analyzer_app:delete_all_repositories' %}" title="Delete all">
			<i class="fa fa-trash"></i>
		</button>
	</div>
  </nav>
{% endblock page_header %}


{% block content %}
		
		<table class="table">
			<thead class="thead-dark">
			  <tr>
				<th>Id</th>
				<th>Url</th>
				<th>Actions</th>
			  </tr>
			</thead>
			<tbody>
			{% for repo in repositories %}
			<tr class="text-light">
				<td>{{ repo.id }}</td>
				<td>{{ repo }}</td>
				<td>
					<div class="row">
						<a href="{% url 'python_code_analyzer_app:repository' repo.id %}" class="btn btn-dark" title="View analyzes"><i class="fa fa-eye"></i></a>
						<button class="btn btn-dark delete-btn" data-url="{% url 'python_code_analyzer_app:delete_repository' repo.id %}" title="Delete">
							<i class="fa fa-trash"></i>
						</button>
					</div>
				</td>
			</tr>
			{% empty %}
				<tr class="text-light">
					<td colspan="3">No repositories have been added yet.</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>


	<!-- pagination -->
	
	<nav class="d-flex justify-content-center" aria-label="Page navigation example">
		<ul class="pagination">
		  {% if repositories.has_previous %}
			<li class="page-item">
				<a class="page-link bg-dark text-light" href="?page=1">First</a>
			</li>
			<li class="page-item">
			  <a class="page-link bg-dark text-light" href="?page={{ repositories.previous_page_number }}">Previous</a>
			</li>
		  {% else %}
			<li class="page-item disabled">
				<a class="page-link bg-dark text-light" href="?page=1">First</a>
			</li>
			<li class="page-item disabled">
			  <a class="page-link  bg-dark text-light" href="#">Previous</a>
			</li>
		  {% endif %}
	
		  {% for num in repositories.paginator.page_range %}
		  	{% if num > repositories.number|add:'-6' and num < repositories.number|add:'6' %}
				{% if repositories.number == num %}
				<li class="page-item active">
					<a class="page-link" href="#">{{ num }} <span class="sr-only">(current)</span></a>
				</li>
				{% else %}
				<li class="page-item">
					<a class="page-link bg-dark text-light" href="?page={{ num }}">{{ num }}</a>
				</li>
				{% endif %}
			{% endif %}
		  {% endfor %}
	
		  {% if repositories.has_next %}
			<li class="page-item">
			  <a class="page-link bg-dark text-light" href="?page={{ repositories.next_page_number }}">Next</a>
			</li>
			<li class="page-item">
				<a class="page-link bg-dark text-light" href="?page={{ repositories.paginator.num_pages }}">Last</a>
			</li>
		  {% else %}
			<li class="page-item disabled">
			  <a class="page-link bg-dark text-light" href="#">Next</a>
			</li>
			<li class="page-item disabled">
				<a class="page-link bg-dark text-light" href="?page={{ repositories.paginator.num_pages }}">Last</a>
			</li>
		  {% endif %}
		</ul>
	  </nav>
{% endblock content %}

python_code_analyzer_app/templates/python_code_analyzer_app/repository.html
{% extends 'python_code_analyzer_app/base.html' %}
{% block page_header %}
<nav class="navbar navbar-dark bg-dark">
	<a  href="javascript:history.go(-1);"  class="btn btn-dark" title="Back"><i class="fa fa-arrow-left"></i></a>
	<span class="navbar-brand mb-0 h1">Repository: <span style="background-color: #5c5c5c">{{ repository }}</span></span>
	<div class="row">
		<form class="form-inline">
			<a  href="{% url 'python_code_analyzer_app:new_analysis' repository.id %}"  class="btn btn-dark" title="New analysis"><i class="fa fa-plus"></i></a>
		
		</form>
		<button class="btn btn-dark delete-all-btn" data-url="{% url 'python_code_analyzer_app:delete_all_analyzes' repository.id %}" title="Delete">
			<i class="fa fa-trash"></i>
		</button>
	</div>
  </nav>
{% endblock page_header %}

{% block content %}
	<table class="table">
		<thead class="thead-dark">
		  <tr>
			<th>Id</th>
			<th>Commit</th>
			<th>Date</th>
			<th>Status</th>
			<th>Actions</th>
		  </tr>
		</thead>
		<tbody>
		{% for analysis in analyzes %}
		<tr class="text-light">
			<td>{{ analysis.id }}</td>
			<td>{{ analysis.commit }}</td>
			<td>{{ analysis.date_added|date:'M d, Y H:i' }}</td>
			<td>{{ analysis.status }}</td>
			<td>
				<div class="row">
				{% if analysis.status == 'PENDING' or analysis.status == 'RUNNING' %}
					<a href="{% url 'python_code_analyzer_app:cancel_analysis' analysis.id %}" class="btn btn-dark" title="Cancel"><i class="fa fa-times"></i></a>
				{% else %}
					<a href="{% url 'python_code_analyzer_app:analysis' analysis.id %}" class="btn btn-dark" title="View results"><i class="fa fa-eye"></i></a>
					<button class="btn btn-dark delete-btn" data-url="{% url 'python_code_analyzer_app:delete_analysis' analysis.id %}" title="Delete">
						<i class="fa fa-trash"></i>
					</button>
				{% endif %}	
				
				</div>
			</td>
		</tr>
		{% empty %}
			<tr>
				<td colspan="5" class="text-light">There are no analyzes for this repository yet.</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
	<!-- pagination -->
	  <nav class="d-flex justify-content-center" aria-label="Page navigation example">
		<ul class="pagination">
		  {% if analyzes.has_previous %}
			<li class="page-item">
				<a class="page-link bg-dark text-light" href="?page=1">First</a>
			</li>
			<li class="page-item">
			  <a class="page-link bg-dark text-light" href="?page={{ analyzes.previous_page_number }}">Previous</a>
			</li>
		  {% else %}
			<li class="page-item disabled">
				<a class="page-link bg-dark text-light" href="?page=1">First</a>
			</li>
			<li class="page-item disabled">
			  <a class="page-link  bg-dark text-light" href="#">Previous</a>
			</li>
		  {% endif %}
	
		  {% for num in analyzes.paginator.page_range %}
		  	{% if num > analyzes.number|add:'-6' and num < analyzes.number|add:'6' %}
				{% if analyzes.number == num %}
				<li class="page-item active">
					<a class="page-link" href="#">{{ num }} <span class="sr-only">(current)</span></a>
				</li>
				{% else %}
				<li class="page-item">
					<a class="page-link bg-dark text-light" href="?page={{ num }}">{{ num }}</a>
				</li>
				{% endif %}
			{% endif %}
		  {% endfor %}
	
		  {% if analyzes.has_next %}
			<li class="page-item">
			  <a class="page-link bg-dark text-light" href="?page={{ analyzes.next_page_number }}">Next</a>
			</li>
			<li class="page-item">
				<a class="page-link bg-dark text-light" href="?page={{ analyzes.paginator.num_pages }}">Last</a>
			</li>
		  {% else %}
			<li class="page-item disabled">
			  <a class="page-link bg-dark text-light" href="#">Next</a>
			</li>
			<li class="page-item disabled">
				<a class="page-link bg-dark text-light" href="?page={{ analyzes.paginator.num_pages }}">Last</a>
			</li>
		  {% endif %}
		</ul>
	  </nav>
{% endblock content %}